### PR TITLE
status screen has exp bar

### PR DESCRIPTION
**Pull request by xCrystal**
bgb00006

### CODE REVIEW

**Comment by xCrystal** [comment]
Not sure why this brought conflicts. I worked over the last updated version of the pokered-gbc repo. I hope it's not too much of an issue to fix whatever the conflicts are anyway.

**Comment by dannye** [comment]
There are conflicts because your repo is 135 commits behind.
Anyway, this is a good idea. I'll look at it more later today.

**Comment by xCrystal** [comment]
oh whoops my fork is indeed over 2 months old. I forked pokered-gbc today but I've just noticed that I had an older fork so it kept the old one without me noticing, my bad.

**Comment by dannye** [comment]
https://github.com/dannye/pokered-gbc/commit/f1483c96f086b1a4bae0041b6106e4ca59406ea8

I merged this, as well as made a few tweaks. I used SCREEN_WIDTH instead of 20, wrapped the new line box coords in "IF GEN_2_GRAPHICS" as to not affect the border with vanilla graphics, and I added a little bit in StatusScreen2 that restores the original border on the second page in gen 2 graphics mode.

Thanks for this, xCrystal.

**Pull request merged**
